[package]
name = "prover"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { path = "../../risc0/risc0/risc0/zkvm" }
risc0-core = { path = "../../risc0/risc0/risc0/core"}
risc0-zkp = { path = "../../risc0/risc0/risc0/zkp"}
serde_json = "*"